"""create content tables
Revision ID: 42116df0ca1f
Revises: 
Create Date: 2026-05-07 12:11:56
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42116df0ca1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('name_ko', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_table('meanings',
    sa.Column('meaning_id', sa.String(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('meaning_id')
    )
    op.create_index(op.f('ix_meanings_meaning_id'), 'meanings', ['meaning_id'], unique=False)
    op.create_index(op.f('ix_meanings_word'), 'meanings', ['word'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=True)
    op.create_table('learning_sets',
    sa.Column('set_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.create_index(op.f('ix_learning_sets_category_id'), 'learning_sets', ['category_id'], unique=False)
    op.create_index(op.f('ix_learning_sets_set_id'), 'learning_sets', ['set_id'], unique=False)
    op.create_table('sentences',
    sa.Column('sentence_id', sa.String(), nullable=False),
    sa.Column('meaning_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('highlight', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meaning_id'], ['meanings.meaning_id'], ),
    sa.PrimaryKeyConstraint('sentence_id')
    )
    op.create_index(op.f('ix_sentences_meaning_id'), 'sentences', ['meaning_id'], unique=False)
    op.create_index(op.f('ix_sentences_sentence_id'), 'sentences', ['sentence_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('meaning_id', sa.String(), nullable=False),
    sa.Column('polysemy_word', sa.String(), nullable=False),
    sa.Column('prompt_sentence', sa.Text(), nullable=False),
    sa.Column('pronunciation_target', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('card_order', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meaning_id'], ['meanings.meaning_id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['learning_sets.set_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_quizzes_card_id'), 'quizzes', ['card_id'], unique=False)
    op.create_index(op.f('ix_quizzes_meaning_id'), 'quizzes', ['meaning_id'], unique=False)
    op.create_index(op.f('ix_quizzes_set_id'), 'quizzes', ['set_id'], unique=False)
    op.create_table('quiz_choices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('choice_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('meaning_id', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['quizzes.card_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_choices_card_id'), 'quiz_choices', ['card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_choices_card_id'), table_name='quiz_choices')
    op.drop_table('quiz_choices')
    op.drop_index(op.f('ix_quizzes_set_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_meaning_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_card_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_sentences_sentence_id'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_meaning_id'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_index(op.f('ix_learning_sets_set_id'), table_name='learning_sets')
    op.drop_index(op.f('ix_learning_sets_category_id'), table_name='learning_sets')
    op.drop_table('learning_sets')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_meanings_word'), table_name='meanings')
    op.drop_index(op.f('ix_meanings_meaning_id'), table_name='meanings')
    op.drop_table('meanings')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
