services:
  db:
    image: postgres:16
    container_name: arirang-postgres
    restart: always
    environment:
      POSTGRES_DB: arirang
      POSTGRES_USER: arirang_user
      POSTGRES_PASSWORD: arirang_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
